name: packages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on:
      - codebuild-packages-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: actions/setup-node@v4




