name: packages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on:
      - codebuild-packages-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: actions/setup-node@v4
      - run: npm install -g aws-cdk
      - run: npm install -g aws-cdk-lib
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt --upgrade
      - run: cdk version
      - run: npm list -g aws-cdk-lib
