name: packages
on: [push]
jobs:
  deploy:
    runs-on:
      - codebuild-packages-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install -g aws-cdk
      - run: npm install -g aws-cdk-lib
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt --upgrade
      - run: cdk version
      - run: npm list -g aws-cdk-lib


